spring.application.name=appService
#spring.datasource.url=jdbc:sqlserver://employee-db-server.database.windows.net:1433;database=employee_db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.url=jdbc:sqlserver://employee-db-server.database.windows.net:1433;database=employee-db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=employee-db-admin
spring.datasource.password=Maxil123
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
